language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install git+https://github.com/skippyprime/assertpy.git@metaclasses
  - pip install coveralls
  - pip install -r development.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6* ]]; then travis_retry pip install ordereddict; fi
# command to run tests
script: py.test --cov-report term-missing --cov=figtree tests/
after_success:
  - coveralls
notifications:
  email:
    - skippydev007@gmail.com
